(cl:defpackage binpicking_msgs-srv
  (:use )
  (:export
   "CALCULATEOBJECTPOSEFROMPOINTCLOUD"
   "<CALCULATEOBJECTPOSEFROMPOINTCLOUD-REQUEST>"
   "CALCULATEOBJECTPOSEFROMPOINTCLOUD-REQUEST"
   "<CALCULATEOBJECTPOSEFROMPOINTCLOUD-RESPONSE>"
   "CALCULATEOBJECTPOSEFROMPOINTCLOUD-RESPONSE"
   "CAPTUREPOINTCLOUD"
   "<CAPTUREPOINTCLOUD-REQUEST>"
   "CAPTUREPOINTCLOUD-REQUEST"
   "<CAPTUREPOINTCLOUD-RESPONSE>"
   "CAPTUREPOINTCLOUD-RESPONSE"
  ))

