// Generated by gencpp from file binpicking_msgs/CalculateObjectposeFromPointcloud.msg
// DO NOT EDIT!


#ifndef BINPICKING_MSGS_MESSAGE_CALCULATEOBJECTPOSEFROMPOINTCLOUD_H
#define BINPICKING_MSGS_MESSAGE_CALCULATEOBJECTPOSEFROMPOINTCLOUD_H

#include <ros/service_traits.h>


#include <binpicking_msgs/CalculateObjectposeFromPointcloudRequest.h>
#include <binpicking_msgs/CalculateObjectposeFromPointcloudResponse.h>


namespace binpicking_msgs
{

struct CalculateObjectposeFromPointcloud
{

typedef CalculateObjectposeFromPointcloudRequest Request;
typedef CalculateObjectposeFromPointcloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalculateObjectposeFromPointcloud
} // namespace binpicking_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::binpicking_msgs::CalculateObjectposeFromPointcloud > {
  static const char* value()
  {
    return "243cf703a4ab0240271683f44bc2d4c6";
  }

  static const char* value(const ::binpicking_msgs::CalculateObjectposeFromPointcloud&) { return value(); }
};

template<>
struct DataType< ::binpicking_msgs::CalculateObjectposeFromPointcloud > {
  static const char* value()
  {
    return "binpicking_msgs/CalculateObjectposeFromPointcloud";
  }

  static const char* value(const ::binpicking_msgs::CalculateObjectposeFromPointcloud&) { return value(); }
};


// service_traits::MD5Sum< ::binpicking_msgs::CalculateObjectposeFromPointcloudRequest> should match 
// service_traits::MD5Sum< ::binpicking_msgs::CalculateObjectposeFromPointcloud > 
template<>
struct MD5Sum< ::binpicking_msgs::CalculateObjectposeFromPointcloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::binpicking_msgs::CalculateObjectposeFromPointcloud >::value();
  }
  static const char* value(const ::binpicking_msgs::CalculateObjectposeFromPointcloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::binpicking_msgs::CalculateObjectposeFromPointcloudRequest> should match 
// service_traits::DataType< ::binpicking_msgs::CalculateObjectposeFromPointcloud > 
template<>
struct DataType< ::binpicking_msgs::CalculateObjectposeFromPointcloudRequest>
{
  static const char* value()
  {
    return DataType< ::binpicking_msgs::CalculateObjectposeFromPointcloud >::value();
  }
  static const char* value(const ::binpicking_msgs::CalculateObjectposeFromPointcloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::binpicking_msgs::CalculateObjectposeFromPointcloudResponse> should match 
// service_traits::MD5Sum< ::binpicking_msgs::CalculateObjectposeFromPointcloud > 
template<>
struct MD5Sum< ::binpicking_msgs::CalculateObjectposeFromPointcloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::binpicking_msgs::CalculateObjectposeFromPointcloud >::value();
  }
  static const char* value(const ::binpicking_msgs::CalculateObjectposeFromPointcloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::binpicking_msgs::CalculateObjectposeFromPointcloudResponse> should match 
// service_traits::DataType< ::binpicking_msgs::CalculateObjectposeFromPointcloud > 
template<>
struct DataType< ::binpicking_msgs::CalculateObjectposeFromPointcloudResponse>
{
  static const char* value()
  {
    return DataType< ::binpicking_msgs::CalculateObjectposeFromPointcloud >::value();
  }
  static const char* value(const ::binpicking_msgs::CalculateObjectposeFromPointcloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BINPICKING_MSGS_MESSAGE_CALCULATEOBJECTPOSEFROMPOINTCLOUD_H
