// Generated by gencpp from file binpicking_msgs/CapturePointcloudRequest.msg
// DO NOT EDIT!


#ifndef BINPICKING_MSGS_MESSAGE_CAPTUREPOINTCLOUDREQUEST_H
#define BINPICKING_MSGS_MESSAGE_CAPTUREPOINTCLOUDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace binpicking_msgs
{
template <class ContainerAllocator>
struct CapturePointcloudRequest_
{
  typedef CapturePointcloudRequest_<ContainerAllocator> Type;

  CapturePointcloudRequest_()
    : dummy(0)  {
    }
  CapturePointcloudRequest_(const ContainerAllocator& _alloc)
    : dummy(0)  {
  (void)_alloc;
    }



   typedef int32_t _dummy_type;
  _dummy_type dummy;





  typedef boost::shared_ptr< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CapturePointcloudRequest_

typedef ::binpicking_msgs::CapturePointcloudRequest_<std::allocator<void> > CapturePointcloudRequest;

typedef boost::shared_ptr< ::binpicking_msgs::CapturePointcloudRequest > CapturePointcloudRequestPtr;
typedef boost::shared_ptr< ::binpicking_msgs::CapturePointcloudRequest const> CapturePointcloudRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace binpicking_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'binpicking_msgs': ['/home/student/test_ws/src/Binpick/binpicking_msgs/msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/melodic/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'shape_msgs': ['/opt/ros/melodic/share/shape_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/melodic/share/octomap_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/melodic/share/object_recognition_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da6c21c6d030841e7157c3016b0292a3";
  }

  static const char* value(const ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda6c21c6d030841eULL;
  static const uint64_t static_value2 = 0x7157c3016b0292a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "binpicking_msgs/CapturePointcloudRequest";
  }

  static const char* value(const ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 dummy\n"
;
  }

  static const char* value(const ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dummy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CapturePointcloudRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::binpicking_msgs::CapturePointcloudRequest_<ContainerAllocator>& v)
  {
    s << indent << "dummy: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dummy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BINPICKING_MSGS_MESSAGE_CAPTUREPOINTCLOUDREQUEST_H
