// Generated by gencpp from file binpicking_msgs/CapturePointcloud.msg
// DO NOT EDIT!


#ifndef BINPICKING_MSGS_MESSAGE_CAPTUREPOINTCLOUD_H
#define BINPICKING_MSGS_MESSAGE_CAPTUREPOINTCLOUD_H

#include <ros/service_traits.h>


#include <binpicking_msgs/CapturePointcloudRequest.h>
#include <binpicking_msgs/CapturePointcloudResponse.h>


namespace binpicking_msgs
{

struct CapturePointcloud
{

typedef CapturePointcloudRequest Request;
typedef CapturePointcloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CapturePointcloud
} // namespace binpicking_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::binpicking_msgs::CapturePointcloud > {
  static const char* value()
  {
    return "315ec3f0ae151d189c2cc77d1ed9084f";
  }

  static const char* value(const ::binpicking_msgs::CapturePointcloud&) { return value(); }
};

template<>
struct DataType< ::binpicking_msgs::CapturePointcloud > {
  static const char* value()
  {
    return "binpicking_msgs/CapturePointcloud";
  }

  static const char* value(const ::binpicking_msgs::CapturePointcloud&) { return value(); }
};


// service_traits::MD5Sum< ::binpicking_msgs::CapturePointcloudRequest> should match 
// service_traits::MD5Sum< ::binpicking_msgs::CapturePointcloud > 
template<>
struct MD5Sum< ::binpicking_msgs::CapturePointcloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::binpicking_msgs::CapturePointcloud >::value();
  }
  static const char* value(const ::binpicking_msgs::CapturePointcloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::binpicking_msgs::CapturePointcloudRequest> should match 
// service_traits::DataType< ::binpicking_msgs::CapturePointcloud > 
template<>
struct DataType< ::binpicking_msgs::CapturePointcloudRequest>
{
  static const char* value()
  {
    return DataType< ::binpicking_msgs::CapturePointcloud >::value();
  }
  static const char* value(const ::binpicking_msgs::CapturePointcloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::binpicking_msgs::CapturePointcloudResponse> should match 
// service_traits::MD5Sum< ::binpicking_msgs::CapturePointcloud > 
template<>
struct MD5Sum< ::binpicking_msgs::CapturePointcloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::binpicking_msgs::CapturePointcloud >::value();
  }
  static const char* value(const ::binpicking_msgs::CapturePointcloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::binpicking_msgs::CapturePointcloudResponse> should match 
// service_traits::DataType< ::binpicking_msgs::CapturePointcloud > 
template<>
struct DataType< ::binpicking_msgs::CapturePointcloudResponse>
{
  static const char* value()
  {
    return DataType< ::binpicking_msgs::CapturePointcloud >::value();
  }
  static const char* value(const ::binpicking_msgs::CapturePointcloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BINPICKING_MSGS_MESSAGE_CAPTUREPOINTCLOUD_H
