set(robotiq_3f_gripper_articulated_msgs_MESSAGE_FILES "/home/student/test_ws/src/ros_packages/robotiq/robotiq_3f_gripper_articulated_msgs/msg/Robotiq3FGripperRobotInput.msg;/home/student/test_ws/src/ros_packages/robotiq/robotiq_3f_gripper_articulated_msgs/msg/Robotiq3FGripperRobotOutput.msg")
set(robotiq_3f_gripper_articulated_msgs_SERVICE_FILES "")
